### ISSUE TITLE
We need to ensure best-practice compatibility with ACES

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_Tabular_AutoML#34]
We need to ensure we can run ACES once from the command line for a given task, and never need to reference it (or even have it supported or installed) in this repo directly. This will ensure greater flexibility over the possible systems one can use to generate task dataframes (e.g., ATLAS, PIC-SURE, etc.)

**Comment by Oufattole** [comment]
We rely on the meds-label schema ever since issue #55 was addressed, resolving this issue.
