### ISSUE TITLE
Updating column names and such to be consistent with MEDS v0.3 for the data schema (`timestamp` -> `time`, `numerical_value` -> `numeric_value`)

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_Tabular_AutoML#56]

**Comment by mmcdermott** [comment]
@teyaberg it looks like you updated the data schema in branch 55 but not the task df schema (https://github.com/Medical-Event-Data-Standard/meds/blob/main/src/meds/schema.py#L48) -- is that right?

**Comment by mmcdermott** [comment]
Also tests are failing due to your changes: https://github.com/mmcdermott/MEDS_Tabular_AutoML/actions/runs/10334434763/job/28607898000?pr=65

**Comment by teyaberg** [comment]
@mmcdermott fixed the tests (https://github.com/mmcdermott/MEDS_Tabular_AutoML/actions/runs/10334622435) and yes, you are correct. However, I am unsure if we need to update the task df schema since we rely on ACES to handle task definition and window extraction.

**Comment by mmcdermott** [comment]
do we still run ACES in this codebase? We don't just read in from a task dataframe? at some point we should read in a label dataframe and that schema will need to update.

**Comment by mmcdermott** [comment]
@teyaberg the tests create label dataframes with the old column names -- I'm correcting this now in my changes for #58, so these names are definitely used somewhere.

**Comment by teyaberg** [comment]
we don't actually call aces in this codebase. We extract the labels and match the valid events to our tabularized rows in an extract_aces_task script in our MIMIC repo. This is where we rename and match (https://github.com/mmcdermott/MEDS_TAB_MIMIC_IV/blob/76d9fc01f7f196dfeb35b8ff4be9d6529cfdc5a2/aces_task_extraction.py#L79)

**Comment by mmcdermott** [comment]
I've separated out label schema stuff to be tracked in #66. Closing this issue as you've handled the data part.
